apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat-og
  namespace: openshift-operators-redhat
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
spec:
  channel: stable
  name: loki-operator
  installPlanApproval: Automatic #Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
