apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../lokistack
commonAnnotations:
  environment: non-prod
patches:
  - target:
      group: loki.grafana.com
      version: v1
      kind: LokiStack
      name: logging-lokistack
    patch: |-
      - op: replace
        path: /spec/storage/secret/name
        value: secret-name
  - target:
      group: loki.grafana.com
      version: v1
      kind: LokiStack
      name: logging-lokistack
    patch: |-
      - op: replace
        path: /spec/limits/global/ingestion/perStreamRateLimit
        value: 8
  - target:
      group: loki.grafana.com
      version: v1
      kind: LokiStack
      name: logging-lokistack
    patch: |-
      - op: replace
        path: /spec/limits/global/ingestion/perStreamRateLimitBurst
        value: 20
