apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-lokistack
  namespace: openshift-logging
  labels:
    component: cluster-logging
    cluster-logging/component: lokistack
    cluster-logging.lokistack/size: 1x.small
spec:
  size: 1x.small
  storage:
    schemas:
    - version: v12
      effectiveDate: '2022-06-01'
    secret:
      name: mz-loki-sa
      type: gcs
  storageClassName: standard-csi
  tenants:
    mode: openshift-logging
  template:
     compactor:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     distributor:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     gateway:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     indexGateway:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     ingester:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     querier:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'
     queryFrontend:
       nodeSelector: 
         node-role.kubernetes.io/logging: ""
       tolerations:
         - effect: NoSchedule
           key: logging
           value: 'true'