apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    component: cluster-logging
    cluster-logging/component: clusterlogging-instance
    cluster-logging/logstore: elasticsearch
    cluster-logging/visualization: kibana
    cluster-logging/collection: fluentd
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io: logging
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io
        value: logging
      storage:
        storageClassName: standard
        size: 200G
      resources:
        limits:
          memory: 16Gi
        requests:
          memory: 16Gi
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: SingleRedundancy
  visualization:
    type: kibana
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io: logging
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io
        value: logging
  collection:
    logs:
      type: fluentd
      fluentd:
        tolerations:
        - operator: Exists # will deploy to ALL nodes, master + infra included