apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    component: cluster-logging
    cluster-logging/component: logging-instance
    cluster-logging/logstore: lokistack
    cluster-logging/visualization: logging-view-plugin
    cluster-logging/collection: fluentd
spec:
  managementState: Managed
  logStore:
    type: lokistack
    lokistack:
      name: logging-lokistack
  collection:
    logs:
      type: fluentd
      fluentd:
        tolerations:
          - operator: Exists
